build-qt6/avrpioremote opt/avrpioremote
../src/*.json  opt/avrpioremote
../src/images/AVRPioRemote.png opt/avrpioremote/
../src/theme/* opt/avrpioremote/theme
build-qt6/avrpioremote.desktop usr/share/applications
../src/images/AVRPioRemote.png        usr/share/icons/hicolor/256x256/apps/
../src/images/AVRPioRemote.png        usr/share/icons/hicolor/48x48/apps/
../src/images/AVRPioRemote.png        usr/share/icons/hicolor/32x32/apps/