#!/bin/bash -x

DIR=$PWD
cd ..
NAME=$(basename "$PWD")
cd $DIR

TARGET=/tmp/${NAME}
SOURCE=./
rm -rf $TARGET
mkdir -p $TARGET/debian
#cp ${SOURCE}/debian/ -r $TARGET/
cp -r ../src/ $TARGET/src/
cp  ../* $TARGET/

cd $TARGET
pwd
qmake
make